# wrap_comments = true
# format_strings = true
# combine_control_expr = false
fn_params_layout = "Vertical"
# imports_layout = "Vertical"
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"
# reorder_impl_items = true
# struct_field_align_threshold = 20
# struct_lit_single_line = false
# trailing_comma = "Always"
# trailing_semicolon = false
use_field_init_shorthand = true
max_width = 80
use_small_heuristics = "Max"